require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NsGroupsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # NsGroup. As you add validations to NsGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NsGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ns_groups as @ns_groups" do
      ns_group = NsGroup.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ns_groups)).to eq([ns_group])
    end
  end

  describe "GET #show" do
    it "assigns the requested ns_group as @ns_group" do
      ns_group = NsGroup.create! valid_attributes
      get :show, {:id => ns_group.to_param}, valid_session
      expect(assigns(:ns_group)).to eq(ns_group)
    end
  end

  describe "GET #new" do
    it "assigns a new ns_group as @ns_group" do
      get :new, {}, valid_session
      expect(assigns(:ns_group)).to be_a_new(NsGroup)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ns_group as @ns_group" do
      ns_group = NsGroup.create! valid_attributes
      get :edit, {:id => ns_group.to_param}, valid_session
      expect(assigns(:ns_group)).to eq(ns_group)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new NsGroup" do
        expect {
          post :create, {:ns_group => valid_attributes}, valid_session
        }.to change(NsGroup, :count).by(1)
      end

      it "assigns a newly created ns_group as @ns_group" do
        post :create, {:ns_group => valid_attributes}, valid_session
        expect(assigns(:ns_group)).to be_a(NsGroup)
        expect(assigns(:ns_group)).to be_persisted
      end

      it "redirects to the created ns_group" do
        post :create, {:ns_group => valid_attributes}, valid_session
        expect(response).to redirect_to(NsGroup.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ns_group as @ns_group" do
        post :create, {:ns_group => invalid_attributes}, valid_session
        expect(assigns(:ns_group)).to be_a_new(NsGroup)
      end

      it "re-renders the 'new' template" do
        post :create, {:ns_group => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ns_group" do
        ns_group = NsGroup.create! valid_attributes
        put :update, {:id => ns_group.to_param, :ns_group => new_attributes}, valid_session
        ns_group.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ns_group as @ns_group" do
        ns_group = NsGroup.create! valid_attributes
        put :update, {:id => ns_group.to_param, :ns_group => valid_attributes}, valid_session
        expect(assigns(:ns_group)).to eq(ns_group)
      end

      it "redirects to the ns_group" do
        ns_group = NsGroup.create! valid_attributes
        put :update, {:id => ns_group.to_param, :ns_group => valid_attributes}, valid_session
        expect(response).to redirect_to(ns_group)
      end
    end

    context "with invalid params" do
      it "assigns the ns_group as @ns_group" do
        ns_group = NsGroup.create! valid_attributes
        put :update, {:id => ns_group.to_param, :ns_group => invalid_attributes}, valid_session
        expect(assigns(:ns_group)).to eq(ns_group)
      end

      it "re-renders the 'edit' template" do
        ns_group = NsGroup.create! valid_attributes
        put :update, {:id => ns_group.to_param, :ns_group => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ns_group" do
      ns_group = NsGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => ns_group.to_param}, valid_session
      }.to change(NsGroup, :count).by(-1)
    end

    it "redirects to the ns_groups list" do
      ns_group = NsGroup.create! valid_attributes
      delete :destroy, {:id => ns_group.to_param}, valid_session
      expect(response).to redirect_to(ns_groups_url)
    end
  end

end
